--Creating database
create database Retail_case_study
select * from prod_cat_info
select * from transactions
select * from customer

--Data prepartion and understanding
--1.What is the total number of rows in each of the 3 tables in the database?
select 'customer' as header,COUNT(*) [no_of_rows] from customer
union
select 'prd_cat' as header,COUNT(*) [no_of_rows] from prod_cat_info
union
select 'Transaction' as header,COUNT(*) [no_of_rows] from Transactions

--2.what is the total number of transactions that have a return?
select count(case when [total_amt] <0 then 1 else null end)[num_transaction_return] from Transactions

--3. As you would have noticed, the dates provided across the datasets are not in a correct format. as first steps, pls convert the data variables into valid date formats befor proceeding ahead
alter table customer alter column DOB date
alter table transactions alter column tran_date date

--4. what is the time range of the transaction data available for analysis? show the output in number of days, months and years simultaneously in different columns.

select datediff(day, (select min(tran_date) from Transactions), (select max(tran_date) from Transactions)) as days_diff,
datediff(month, (select min(tran_date) from Transactions), (select max(tran_date) from Transactions)) as months_diff,
datediff(year, (select min(tran_date) from Transactions), (select max(tran_date) from Transactions)) as years_diff

--5. Which product category does the sub_category 'DIY' belong to?
select prod_cat from prod_cat_info
where prod_subcat = 'DIY'

--Data Analysis

--1. Which channel is most frequently used for transactions?
select transaction_id,count(store_type) [most_frequent_tran] from Transactions
group by transaction_id 
order by most_frequent_tran desc


--2. What is the count of Male and Female customers in the database?
select gender,count(gender) [Gender_count] from Customer
group by Gender
having Gender in ('M','F')

--3. From which city do we have the maximum number of customers and how many??
select city_code,count(customer_Id)[city_wise_cust] from Customer
group by city_code
order by city_wise_cust desc 

--4. How many sub_categories are there under the books category??
select  prod_cat, count(prod_subcat)[Num_of_sub] from prod_cat_info
group by prod_cat
having prod_cat = 'Books'

--5. What is the maximum quantity of products ever ordered?
alter table transactions alter column Qty int
select top 1 p.prod_cat,count(Qty)[Quantity] from Transactions t inner join prod_cat_info p on t.prod_cat_code = p.prod_cat_code and p.prod_sub_cat_code =t.prod_subcat_code
group by prod_cat
order by Quantity desc

--6. What is the net total revenue generated in categpries Electronics and Books?
alter table transactions alter column total_amt numeric
select p.prod_cat,sum(total_amt)[total_revenue] from Transactions t inner join prod_cat_info p on t.prod_subcat_code =p.prod_sub_cat_code and t.prod_cat_code =p.prod_cat_code
group by p.prod_cat
having p.prod_cat in ('Electronics','Books')

--7. How many customers have >10 transactions with us, excluding returns?
select count(cust_id) [num_of_tarn] from 
(select cust_id from Transactions
where Qty > 0
group by cust_id
having count(transaction_id)>10) b

--8. What is the combined revenue earned from the 'Electronics' and 'Clothing' categories, from 'Flagship stores'?
select p.prod_cat ,sum(total_amt)[total_revenue] from Transactions t inner join prod_cat_info p on t.prod_cat_code = p.prod_cat_code 
where prod_cat in ('Electronics' ,'Clothing') and Store_type='Flagship store'
group by p.prod_cat

--9.What is the total Revenue generated from 'Male' customers in 'Electronics' category? output should display total revenue by prod sub_cat?
select p.prod_subcat, sum(total_amt)[total_revenue] from customer c inner join transactions t on c.customer_Id = t.cust_id inner join prod_cat_info p on p.prod_cat_code = t.prod_cat_code and p.prod_sub_cat_code = p.prod_sub_cat_code
where Gender ='M' and prod_cat ='Electronics'
group by p.prod_subcat

--10. What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?
select top 5 p.prod_subcat,
           (select (sum(case when total_amt >0 then total_amt else 0 end)/ (select sum(total_amt) from transactions where total_amt >0)*100))[sales_perc],
		   (select (sum(case when total_amt <0 then total_amt else 0 end)/ (select sum(total_amt) from transactions where total_amt <0)*100))[return_percent]
            from Transactions t inner join prod_cat_info p on t.prod_cat_code = p.prod_cat_code and t.prod_subcat_code = p.prod_sub_cat_code
			group by prod_subcat
			order by sales_perc desc

/*11. For all customers aged between 25 to 35 years find what is the net total revenue generated by 
these consumers in last 30 days of transactions from max transaction date available in the data*/

select c.customer_Id, DATEDIFF(YEAR,DOB,tran_date) Age ,(select sum(total_amt))[Total_revenue] from Transactions t inner join Customer c on c.customer_Id = t.cust_id
where DATEDIFF(YEAR,DOB,tran_date) between 25 and 35
group by customer_id, DOB, tran_date
having DATEDIFF(DAY,t.tran_date,(select MAX(tran_date) from transactions))<=30
order by age 

--12. Which product category has seen the max value of returns in the last 3 months of transactions??

select p.prod_cat, sum(case when(total_amt)<0 then total_amt else 0 end)[total_revenue] from Transactions t inner join prod_cat_info p on t.prod_cat_code = p.prod_cat_code and t.prod_subcat_code = p.prod_sub_cat_code
group by prod_cat, tran_date
having tran_date > DATEADD(month,-3,(select max(tran_date) from Transactions))
order by total_revenue asc

--13 Which store-type sells the maximum products; by value of sales amount and quantity sold??
select top 1 Store_type, sum(Qty)[Qty_sold],(select sum(total_amt))[Sales_amount] from Transactions 
group by Store_type
order by Qty_sold desc,sales_amount desc

--14. What are the categories for which average revenue is above the overall average??
select p.prod_cat, avg(total_amt)[avg_revenue] from Transactions t inner join prod_cat_info p on t.prod_cat_code = p.prod_cat_code and t.prod_subcat_code = p.prod_sub_cat_code
group by prod_cat
having avg(total_amt) >( select avg(total_amt) from Transactions)

--15.Find the average and total revenue by each sub category for the categories which are among top 5 categories in terms of quantity sold
select p.prod_cat,p.prod_subcat, avg(total_amt)[avg_revenue],(select sum(total_amt)) [total_revenue] from Transactions t inner join prod_cat_info p on t.prod_cat_code = p.prod_cat_code and t.prod_subcat_code = p.prod_sub_cat_code
where p.prod_cat_code in 
(select top 5 prod_cat_code from Transactions
group by prod_cat_code
order by (select sum(case when(Qty)>0 then Qty else 0 end)) desc)
group by prod_cat,prod_subcat
order by prod_cat,prod_subcat